### PR TITLE
Beautified code and replaced function with =>

### PR DESCRIPTION
**Pull request by YaniCode**

### CODE REVIEW

**Comment by YaniCode** [comment]
Also replaced the function appended to Array with just a simple index with Math.random

**Review by PantheraRed — APPROVED** [review]
Well, not big of a pull request but I approve of it. :+1:

**Comment by YaniCode** [comment]
It's just a basic PR, But quite needed since the "bad" code might make a bad rep for JSU

**Review by Airbus-A330 — APPROVED** [review]

**Comment by Airbus-A330** [comment]
These changes look good. I will merge it later today if Lion Luke doesn't give feedback on it within a reasonable amount of time.

**Pull request merged**
